import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MeowOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preload" href="/images/catgif.gif" as="image" />
        <link rel="preload" href="/images/cat2.gif" as="image" />
        <link rel="preload" href="/images/cat3.gif" as="image" />
        <link rel="preload" href="/images/cat4.gif" as="image" />
        <link rel="preload" href="/images/OSLogo.png" as="image" />
        <link rel="preload" href="/images/icons/calculator.png" as="image" />
        <link rel="preload" href="/images/icons/calendar.png" as="image" />
        <link rel="preload" href="/images/icons/port.png" as="image" />
        <link rel="preload" href="/images/icons/settings.png" as="image" />
      </head>
      <body className="min-h-full flex flex-col dark">{children}</body>
    </html>
  );
}
